### ISSUE TITLE
yvu, yfu 설치 후 import 오류

### ISSUE THREAD

**Issue by may670** [ysBach/AO2019#10]
git bash를 통해 yfu,yvu 모듈을 설치하였는데, 설치 후 import 오류가 발생하였습니다.

    print(allfits[0])
>  WindowsPath('test2/test/NGC2993-0001R.fit')

위와 같이 fit 파일 하나를 지정해놓고, zimshow를 이용해서 이미지를 확인하려고 코드를 다음과 같이 썼는데 오류가 뜹니다.

    hdul = fits.open(allfits[0])
    
    fig, axs = plt.subplots(1, 1, figsize=(5, 6), sharex=False, sharey=False, gridspec_kw=None)
    yvu.zimshow(axs, hdul[0].data)
    plt.tight_layout()

    ---------------------------------------------------------------------------
    AttributeError                            Traceback (most recent call last)
    <ipython-input-35-70a8301ce924> in <module>
          2 
          3 fig, axs = plt.subplots(1, 1, figsize=(5, 6), sharex=False, sharey=False, gridspec_kw=None)
    ----> 4 yvu.zimshow(axs, hdul[0].data)
          5 plt.tight_layout()
    
    AttributeError: module 'ysvisutilpy' has no attribute 'zimshow'

같은 오류가 yfu의 make_summary 코드에서도 발생한 걸 보니, 안에 있는 코드를 읽질 못하는 것 같습니다.

    summary = yfu.make_summary(allfits,keywords = USEFUL_KEYS, output = 'test1.csv',pandas=True)
    ---------------------------------------------------------------------------
    AttributeError                            Traceback (most recent call last)
    <ipython-input-34-81d3c9c18188> in <module>
    ----> 1 summary = yfu.make_summary(allfits,keywords = USEFUL_KEYS, output = 'test1.csv',pandas=True)
    
    AttributeError: module 'ysfitsutilpy' has no attribute 'make_summary'

yfu,yvu 설치가 되고 import도 되는데 안에 있는 코드를 읽질 못합니다. 

yfu,yvu 파일에 들어가 보니 코드는 모두 들어가 있습니다.

재설치도 해보고 껐다 켜봐도 안됩니다.. 

도와주시면 감사하겠습니다.

**Comment by ysBach** [comment]
Hi @may670 !

Could you please test it on a fresh new environment? 

For instance, if you are using conda,

        $ conda create --name test python=3.8 astropy numpy scipy pandas bottleneck fitsio -c conda-forge -y
        $ conda install ccdproc astroscrappy -c astropy -y
        $ conda activate test
        $ cd <path/to/ysfitsutilpy> && git pull && python setup.py install
        $ python
        > import ysfitsutilpy as yfu
        > yfu.make_summary([])

I cannot reproduce your errors with this. 
If you cannot see the error with this new environment, I guess your installation process went wrong at some point (which means I cannot help at this moment unfortunately). You may try to remove anaconda (~/anaconda3) and reinstall it from scratch. I hope the problem is solved soon....

**Comment by may670** [comment]
위 과정 그대로 따라했는데 또 오류가 발생했지만 anaconda를 삭제하고 재설치 하니 정상적으로 작동합니다. 감사합니다!

**Comment by ysBach** [comment]
@may670 Glad it is solved! 
Wish the best with your remaining semester. Take care!

**Comment by may670** [comment]
죄송하지만.. 예전에 없던 또다른 오류가 발생했습니다.

ysvisutilpy는 정상적으로 작동하는데,

    import ysfitsutilpy as yfu
    ---------------------------------------------------------------------------
    ModuleNotFoundError                       Traceback (most recent call last)
    <ipython-input-7-fad4ce758458> in <module>
    ----> 1 import ysfitsutilpy as yfu
    
    <frozen zipimport> in load_module(self, fullname)
    
    ~\anaconda3\lib\site-packages\ysfitsutilpy-0.2.dev0-py3.8.egg\ysfitsutilpy\__init__.py in <module>
          1 from .astrometry import *
    ----> 2 from .airmass import *
          3 from .ccdutil import *
          4 from .combutil import *
          5 from .filemgmt import *
    
    <frozen zipimport> in load_module(self, fullname)
    
    ~\anaconda3\lib\site-packages\ysfitsutilpy-0.2.dev0-py3.8.egg\ysfitsutilpy\airmass.py in <module>
         12 from astropy.time import Time
         13 
    ---> 14 from .hdrutil import get_if_none
         15 
         16 __all__ = ["calc_airmass", "airmass_obs", "airmass_from_hdr"]
    
    <frozen zipimport> in load_module(self, fullname)
    
    ~\anaconda3\lib\site-packages\ysfitsutilpy-0.2.dev0-py3.8.egg\ysfitsutilpy\hdrutil.py in <module>
         13 from astropy.wcs import WCS
         14 
    ---> 15 from .misc import _parse_extension, change_to_quantity, str_now, _parse_data_header, is_list_like
         16 
         17 __all__ = ["add_to_header", "update_process",
    
    <frozen zipimport> in load_module(self, fullname)
    
    ~\anaconda3\lib\site-packages\ysfitsutilpy-0.2.dev0-py3.8.egg\ysfitsutilpy\misc.py in <module>
         11 import bottleneck as bn
         12 import ccdproc
    ---> 13 import fitsio
         14 import numpy as np
         15 from astropy import units as u
    
    ModuleNotFoundError: No module named 'fitsio'


선배님께서 알려주신 과정대로 한 후에 fitsio라는 모듈이 없다고 뜹니다 혹시 어떻게 원래대로 돌릴까요..? anaconda 재설치한 후에 `pip install fitsio fitsio` 를 해봐도 알 수 없는 이유로 설치에 실패합니다.ㅜㅜ
