### ISSUE TITLE
ysfitsutilpy import 도중 module fitsio가 실종되었습니다.

### ISSUE THREAD

**Issue by may670** [ysBach/AO2019#11]
죄송하지만.. 예전에 없던 또다른 오류가 발생했습니다.

ysvisutilpy는 정상적으로 작동하는데,

    import ysfitsutilpy as yfu
    ---------------------------------------------------------------------------
    ModuleNotFoundError                       Traceback (most recent call last)
    <ipython-input-7-fad4ce758458> in <module>
    ----> 1 import ysfitsutilpy as yfu
    
    <frozen zipimport> in load_module(self, fullname)
    
    ~\anaconda3\lib\site-packages\ysfitsutilpy-0.2.dev0-py3.8.egg\ysfitsutilpy\__init__.py in <module>
          1 from .astrometry import *
    ----> 2 from .airmass import *
          3 from .ccdutil import *
          4 from .combutil import *
          5 from .filemgmt import *
    
    <frozen zipimport> in load_module(self, fullname)
    
    ~\anaconda3\lib\site-packages\ysfitsutilpy-0.2.dev0-py3.8.egg\ysfitsutilpy\airmass.py in <module>
         12 from astropy.time import Time
         13 
    ---> 14 from .hdrutil import get_if_none
         15 
         16 __all__ = ["calc_airmass", "airmass_obs", "airmass_from_hdr"]
    
    <frozen zipimport> in load_module(self, fullname)
    
    ~\anaconda3\lib\site-packages\ysfitsutilpy-0.2.dev0-py3.8.egg\ysfitsutilpy\hdrutil.py in <module>
         13 from astropy.wcs import WCS
         14 
    ---> 15 from .misc import _parse_extension, change_to_quantity, str_now, _parse_data_header, is_list_like
         16 
         17 __all__ = ["add_to_header", "update_process",
    
    <frozen zipimport> in load_module(self, fullname)
    
    ~\anaconda3\lib\site-packages\ysfitsutilpy-0.2.dev0-py3.8.egg\ysfitsutilpy\misc.py in <module>
         11 import bottleneck as bn
         12 import ccdproc
    ---> 13 import fitsio
         14 import numpy as np
         15 from astropy import units as u

    ModuleNotFoundError: No module named 'fitsio'
선배님께서 알려주신 과정대로 한 후에 fitsio라는 모듈이 없다고 뜹니다 혹시 어떻게 원래대로 돌릴까요..? anaconda 재설치한 후에 pip install fitsio fitsio 를 해봐도 알 수 없는 이유로 설치에 실패합니다.ㅜㅜ 

감사합니다.

**Comment by ysBach** [comment]
(1) could you install it via
``conda install fitsio -c conda-forge`` OR ``pip3 install fitsio``?
(2) If that doesn't help, could you please do

    cd ~ && git clone https://github.com/esheldon/fitsio.git && cd fitsio && pip install -e .

and restart the kernel to see if it works?

**Comment by may670** [comment]
2번째 방법으로 해결되었습니다. 감사합니다!!!
