### ISSUE TITLE
Issue about hw05 & hw06

### ISSUE THREAD

**Issue by seungukSong** [ysBach/AO2019#2]
In hw06 problem 3, I think that hint '.tale()' should be '.tail()'
In hw05 problem 10, I think that '**2'  in the code below
'data_ci = np.random.normal(loc=?, scale=?**2, size=(n_sample, 100000))'
isn't needed.
Because 'scale' in np.random.normal means standard deviation, not the variance.
(Source : https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.normal.html)

**Comment by ysBach** [comment]
Thanks for the report.

Both of them, you are right. Will correct soon.
