### ISSUE TITLE
issue about HW-astropy_01-fits.md

### ISSUE THREAD

**Issue by femtomino** [ysBach/AO2019#7]
`imgrid_kw` already have `nrows_ncols` value, so `grid = ImageGrid(fig, 111, nrows_ncols=(1, 1), **imgrid_kw)` in Q2-9 and Q2-11 return `TypeError: type object got multiple values for keyword argument 'nrows_ncols'`

**Comment by ysBach** [comment]
Thanks for the report. I will update the file very soon.
