### ISSUE TITLE
Some issues about HW-master_calibration_01.md

### ISSUE THREAD

**Issue by femtomino** [ysBach/AO2019#8]
Instructions
Start of the code
We use `np.unique` to make `dark_exptimes` so add `import numpy as np` will be happy :)

`CALDIR` directory is used in Q3-1 but it is not defined

Problems
1.6 Hint 2
round bracket in the end of a code cause error
`...1f}.fits")`  -> `...1f}.fits"` 

3.4
`for dark_exptime in dark_exptimes[-1:]:`
This only makes `mdark_60.0.fits` but we need other ones (`9,12,15,20`) to subtract for flats.
-> `for dark_exptime in dark_exptimes:` (We sorted `dark_exptimes` so Q3.5 will work fine with this.)

3.7
After `normalize_median=True`, most of values are around 1. So `dtype='uint16'` makes most of pixel values either 0 or 1.
![image](https://user-images.githubusercontent.com/63769723/82754461-0213cb00-9e08-11ea-88aa-7e23c1cd6b68.png)
Delete `dtype='uint16'` .

4.4 & 4.5
`flat_R.fits` -> `mflat_R.fits`

**Comment by ysBach** [comment]
Thanks for the report @femtomino !
I have confirmed your comments are correct and I corrected all.
sorry for the inconvenience.
